### ISSUE TITLE
Add JuliaMono webfonts to /assets/ ?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/www.julialang.org#1272]
We could add the JuliaMono webfonts to the julialang.org website. They could live in, say,  `www.julialang.org/assets/fonts/JuliaMono/webfonts/` as the files:

```
JuliaMono-Black.woff2
JuliaMono-Bold.woff2
JuliaMono-BoldLatin.woff2
JuliaMono-ExtraBold.woff2
JuliaMono-Light.woff2
JuliaMono-Medium.woff2
JuliaMono-Regular.woff2
JuliaMono-RegularLatin.woff2
JuliaMono-SemiBold.woff2
```

The total size of this new directory would be about 5MB. People would then be able to use the fonts for package documentation, blog posts, [etc](https://github.com/search?o=desc&q=juliamono+language%3Acss&s=indexed&type=Code).. To do this, they would add something like this to a CSS file:

```css
@font-face {
	font-family: JuliaMono;
	src:
		local('JuliaMono-Regular'),
		url("https://www.julialang.org/assets/fonts/JuliaMono/webfonts/JuliaMono-Regular.woff2");
}
```

I've no idea what the bandwidth would be, or whether that would be a cost/pricing issue? At present, the actual OpenType fonts are [stored on github](https://github.com/cormullion/juliamono), but the webfonts (WOFF) are served from there via the NPM/JavaScript-focussed https://www.jsdelivr.com CDN. It works fine (but I have no more information than that).

There would be no visible changes to this website. (And I'm not saying that people should start using the fonts anywhere, unless they want to. 😄) 

I don't know whether you would want a disclaimer in the directory somewhere to the effect that the fonts aren't "official"? Although it does promote Julia, in a way...
